### ISSUE TITLE
GetDownloadUriAsync Exception

### ISSUE THREAD

**Issue by marcobiraghi** [flagbug/YoutubeExtractor#101]
"YoutubeExtractor.YoutubeParseException

Could not parse the Youtube page for URL http://youtube.com/watch?v=pTJQRFnkeFw
This may be due to a change of the Youtube page structure."

Trying to get YouTube video's link in Windows Phone 8.1 RT application

**Comment by flagbug** [comment]
Should be fixed with https://github.com/flagbug/YoutubeExtractor/pull/151
