### ISSUE TITLE
Setting output mp3 quality

### ISSUE THREAD

**Issue by defiler007** [flagbug/YoutubeExtractor#102]
Congrats for your library!

Only one question, how can I set output quality of an mp3 from my form?

**Comment by flagbug** [comment]
Each `VideoInfo` object has a `AudioBitrate` property that returns the bitrate in kbit/s

**Comment by defiler007** [comment]
So, in order to produce, eg an 256kbps mp3 file from a video I will need to select a video of a matching bitrate from the videoInfo collection?

**Comment by flagbug** [comment]
Yes

**Comment by defiler007** [comment]
Ok got it. So if a desired output bitrate does not exist in the video collection? Can't there be a conversion? eg from 320 to 256kbps

**Comment by flagbug** [comment]
You'll have to do that for yourself, sorry

**Comment by defiler007** [comment]
Ok I'm covered thanks for your lightning fast replies!
