### ISSUE TITLE
YoutubeParseException

### ISSUE THREAD

**Issue by spasarto** [flagbug/YoutubeExtractor#107]
https://www.youtube.com/watch?v=Du0nUG2YiSA
https://www.youtube.com/watch?v=c5nqV2MFedU
https://www.youtube.com/watch?v=UNubDtawVsg
https://www.youtube.com/watch?v=ZZqHta6FRxM
https://www.youtube.com/watch?v=oPZHmy4ZQLk
https://www.youtube.com/watch?v=k5QWIw0hrA0
https://www.youtube.com/watch?v=b_ftD-6fGnM
https://www.youtube.com/watch?v=NelhkdTgb0M
https://www.youtube.com/watch?v=ZL53g2LKtIk
https://www.youtube.com/watch?v=vWBRujpQtic
https://www.youtube.com/watch?v=nNjxHm3nXIc
https://www.youtube.com/watch?v=5VXuN5yg624
https://www.youtube.com/watch?v=9bpMIUw8Yi0
https://www.youtube.com/watch?v=ZtZkp6brUa8
https://www.youtube.com/watch?v=Io4BprTQGjc
https://www.youtube.com/watch?v=vBjcZjdHu3Q
https://www.youtube.com/watch?v=gg3NO3FyMYs
https://www.youtube.com/watch?v=O8j-I0gzLOM
https://www.youtube.com/watch?v=CFJrbDLPI5c
https://www.youtube.com/watch?v=vv25G6i1uEk
https://www.youtube.com/watch?v=eBEQ5fClgIs
https://www.youtube.com/watch?v=9T7EkO6oO2g
https://www.youtube.com/watch?v=dm5elAJKSh8
https://www.youtube.com/watch?v=7ijfQSN4hZg
https://www.youtube.com/watch?v=QwKQvoq9sBE
https://www.youtube.com/watch?v=eNtsUisXRmg

**Comment by flagbug** [comment]
These videos are age-restricted, which YoutubeExtractor can't handle
