### ISSUE TITLE
Another Test Case that Failed

### ISSUE THREAD

**Issue by dev-enthusiast** [flagbug/YoutubeExtractor#109]
Here is another URL that YoutubeExtractor has problem with:

https://www.youtube.com/watch?v=GkD20ajVxnY

It can be viewed online.  But YoutubeExtractor fails to process it.

**Comment by sceiler** [comment]
I believe that is because of httpS. try without the secure. But at the moment I have an issue with and without secure http. I just reported it #111. But before that it worked perfectly.

**Comment by flagbug** [comment]
Should be fixed with https://github.com/flagbug/YoutubeExtractor/pull/151
