### ISSUE TITLE
play stream without saving

### ISSUE THREAD

**Issue by ericboman** [flagbug/YoutubeExtractor#112]
I've been trying to add play feature where you can play the buffered bytes to screen. 
i am currently trying to use a bit larger buffer with circular use [queue to be exact :)] where i consume from one end while filling it from the other end. 

but i have no idea how to manage the connection speeds and bandwidth.

does "VideoDownloadr" classes 
``public override void execute()`` 
method handle adaptive bit ranges as well? if not any idea how to approach it.

Thank you.

**Comment by flagbug** [comment]
The `VideoDownloader` class is designed only for simple user cases where you want to download a file to the disk, so this is not supported, sorry!
