### ISSUE TITLE
Gives Process In Bytes

### ISSUE THREAD

**Issue by mysteryx93** [flagbug/YoutubeExtractor#114]
Edit: The title got mispelled, it should be "Give Progress in Bytes".

Currently, the only way to know the download progress of a file is with ProgressEventArgs.ProgressPercentage. 

Because the audio and video download separately, if I want to display a progress bar for both files, the percentage of each file is not useful. I must know the amount of bytes downloaded and the total amount of bytes in the file.

This would be very simple to implement:
- Add VideoDownloader.DownloadSize
- In YouTubeExtractor.Execute, add: DownloadSize = (int)response.ContentLength;
- Add ProgressEventArgs.ProgressBytes

Thanks!

**Comment by arindamnayak** [comment]
Hey @mysteryx93 , I have added code for your requirement. I have created pull request - #126, here is [detailed log](https://github.com/flagbug/YoutubeExtractor/commit/2ad05cf7361659f4955e4dea1c543c1d0263f9b7).

If that pull request merged by @flagbug , and released via Nuget, you can start using that.

**Comment by flagbug** [comment]
I'm not going to make any more changes to the existing video and audio download code, sorry!
