### ISSUE TITLE
QUESTION: Should I implement NReco.VideoConverter?

### ISSUE THREAD

**Issue by Kimmax** [flagbug/YoutubeExtractor#115]
First of all: You did a good job!
Second: Im using this library in my own project and kind of hacked the NReco.VideoConverter in this to be able to extract high quality audio streams from the videos (Even works with .mp4).
Is anybody interested to see a clean implementation of it?
I would do it, mine works but I would redo a clean version of it and make a pull request, but only if some of you guys are interested in it, u know life isn't endless :P 
So let me know!

**Comment by Kimmax** [comment]
Sry for opening a issue tho, but I didn't know how to ask otherwise.

**Comment by UngarMax** [comment]
Oh wow, that could be completely useful since direct audio downloads are low quality! I already made some research and thought about converting the videos to audio files using ffmpeg.dll (via command args), but with NReco.VideoConverter would be much better for sure.

**Comment by Kimmax** [comment]
As requested, I am done I think, faster than expected, no big deal at all.
Pull request #116 is open, now let's wait or clone from my fork.

**Comment by UngarMax** [comment]
Awesome! Much appreciated for your implementations :)
An off-topic question, though: does anybody know how to get the download speed for a video (excluding any kind of extraction)?

**Comment by flagbug** [comment]
As I stated in #150 , I don't really want YoutubeExtractor to become a fully featured kitchen-and-the-sink library, so audio extraction and video conversion should stay in a separate libary, but thanks for the work you've done!
