### ISSUE TITLE
Could not parse the Youtube page for URL

### ISSUE THREAD

**Issue by tariqalkhassa** [flagbug/YoutubeExtractor#119]
Could not parse the Youtube page for this URL:

https://www.youtube.com/watch?v=tQmEd_UeeIk

**Comment by UngarMax** [comment]
Try parsing the URL with 'http' instead of 'https':

http://www.youtube.com/watch?v=tQmEd_UeeIk

**Comment by tariqalkhassa** [comment]
didn't work..

**Comment by htnha** [comment]
I have the same problem :(

**Comment by htnha** [comment]
More examples:

**Comment by htnha** [comment]
https://www.youtube.com/watch?v=7uG6E6bVKU0

**Comment by htnha** [comment]
https://www.youtube.com/watch?v=FndmvPkI1Ms

It doesn't work for all VEVO videos

**Comment by tariqalkhassa** [comment]
your links are working for me
anyway I changed the method GetAdaptiveStreamMap at DownloadUrlResolver class to be like:
private static string GetAdaptiveStreamMap(JObject json)
        {
            JToken streamMap;
            try
            {
                streamMap = json["args"]["adaptive_fmts"];
                return streamMap.ToString();
            }
            catch
            {
                streamMap = json["args"]["url_encoded_fmt_stream_map"];
                return streamMap.ToString();
            }
        }


and changed the third line of the method ExtractDownloadUrls at the same class to be like
splitByUrls = splitByUrls.Concat(adaptiveFmtSplitByUrls).Distinct().ToArray();


and now it's working for all videos for me :)

**Comment by Corbel** [comment]
I made the changes but this (http://www.youtube.com/watch?v=o1U5IY8kynI) link isn't working for me.

**Comment by skkeeper** [comment]
The fix worked for me too.

@tariqalkhassa Are you going to submit a pull request? I would but I don't want to take credit for it.

**Comment by tariqalkhassa** [comment]
@skkeeper  I didn't know how to submit it :S
I made a fork and I have this link now
https://github.com/tariqalkhassa/YoutubeExtractor/blob/master/YoutubeExtractor/YoutubeExtractor/DownloadUrlResolver.cs

**Comment by e4stwood** [comment]
His code provides an error of - illegal characters in path. Definitely not an error on my part. Checked, rechecked and rechecked

**Comment by flagbug** [comment]
Should be fixed with https://github.com/flagbug/YoutubeExtractor/pull/151
