### ISSUE TITLE
No sound for 1080 Youtube Video

### ISSUE THREAD

**Issue by morefun0302** [flagbug/YoutubeExtractor#120]
After downloading 1080p YouTube video, the video does not contain and sound channels.

**Comment by di48l069** [comment]
@morefun0302 @flagbug Ya i'm having the same problem

**Comment by morefun0302** [comment]
Found a solution:
use if (!videoInfo.CanExtractAudio)
{
//download the audio mp3, then use ffmpeg to combine video and audio channels
}
