### ISSUE TITLE
Unable to parse URLs

### ISSUE THREAD

**Issue by Gopichandar** [flagbug/YoutubeExtractor#122]
When I try to download youtube URL, I am getiing the following exception.

Could not parse the Youtube page for URL http://youtube.com/watch?v=lBmb_3Uv5xI

This may be due to a change of the Youtube page structure.

Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues

**Comment by UngarMax** [comment]
It happened to me a few days ago but it seems -at least for me- to be working again.

**Comment by flagbug** [comment]
Should be fixed with https://github.com/flagbug/YoutubeExtractor/pull/151
