### ISSUE TITLE
Some VideoType/resolution combos end with problems.

### ISSUE THREAD

**Issue by aguythere** [flagbug/YoutubeExtractor#123]
While videos with selected resolutions above and below 360 can and will download, I have found that, for some formats (from here on I'll be calling VideoTypes (Mp4, Flash, etc) formats), it will not play correctly. Problems vary, however VLC (and I imagine other video players as well) cannot play the downloaded videos. Occasionally, browsers can (without audio).

Example URL: http://www.youtube.com/watch?v=O3UBOOZw-FE

List of working Format/Resolution combos:
     
    //For some formats, limited testing was done. Updates will come as further testing is performed.
    Mp4: only 360
    Mobile: 240, 144, possibly more
    Flash: 240, possibly more
    WebM: 360, possibly more

For the sake of this discussion, I'll be using the code from the example program, though the majority of my testing is done using custom code. If you'd like to review my custom code, I'll furnish it on request.

Just so everything is clear, this is the example code I am using:

    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Text.RegularExpressions;
    using YoutubeExtractor;

    namespace ExampleApplication
    {
    internal class Program
    {
        private static void DownloadAudio(IEnumerable<VideoInfo> videoInfos)
        {
            /*
             * We want the first extractable video with the highest audio quality.
             */
            VideoInfo video = videoInfos
                .Where(info => info.CanExtractAudio)
                .OrderByDescending(info => info.AudioBitrate)
                .First();

            /*
             * If the video has a decrypted signature, decipher it
             */
            if (video.RequiresDecryption)
            {
                DownloadUrlResolver.DecryptDownloadUrl(video);
            }

            /*
             * Create the audio downloader.
             * The first argument is the video where the audio should be extracted from.
             * The second argument is the path to save the audio file.
             */

            var audioDownloader = new AudioDownloader(video,
                Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
                RemoveIllegalPathCharacters(video.Title) + video.AudioExtension));

            // Register the progress events. We treat the download progress as 85% of the progress
            // and the extraction progress only as 15% of the progress, because the download will
            // take much longer than the audio extraction.
            audioDownloader.DownloadProgressChanged += (sender, args) => Console.WriteLine(args.ProgressPercentage * 0.85);
            audioDownloader.AudioExtractionProgressChanged += (sender, args) => Console.WriteLine(85 + args.ProgressPercentage * 0.15);

            /*
             * Execute the audio downloader.
             * For GUI applications note, that this method runs synchronously.
             */
            audioDownloader.Execute();
        }

        private static void DownloadVideo(IEnumerable<VideoInfo> videoInfos)
        {
            /*
             * Select the first .mp4 video with 360p resolution
             */
            VideoInfo video = videoInfos
                .First(info => info.VideoType == VideoType.Mp4 && info.Resolution == 0);

            /*
             * If the video has a decrypted signature, decipher it
             */
            if (video.RequiresDecryption)
            {
                DownloadUrlResolver.DecryptDownloadUrl(video);
            }

            /*
             * Create the video downloader.
             * The first argument is the video to download.
             * The second argument is the path to save the video file.
             */
            var videoDownloader = new VideoDownloader(video,
                Path.Combine("G:\\Moved User Files\\downloaded videos\\",
                RemoveIllegalPathCharacters(video.Title) + video.VideoExtension));

            // Register the ProgressChanged event and print the current progress
            videoDownloader.DownloadProgressChanged += (sender, args) => Console.WriteLine(args.ProgressPercentage);

            /*
             * Execute the video downloader.
             * For GUI applications note, that this method runs synchronously.
             */
            videoDownloader.Execute();
        }

        private static void Main()
        {
            // Our test youtube link
            const string link = "http://www.youtube.com/watch?v=O3UBOOZw-FE";

            /*
             * Get the available video formats.
             * We'll work with them in the video and audio download examples.
             */
            IEnumerable<VideoInfo> videoInfos = DownloadUrlResolver.GetDownloadUrls(link, false);

            //DownloadAudio(videoInfos);
            DownloadVideo(videoInfos);
        }

        private static string RemoveIllegalPathCharacters(string path)
        {
            string regexSearch = new string(Path.GetInvalidFileNameChars()) + new string(Path.GetInvalidPathChars());
            var r = new Regex(string.Format("[{0}]", Regex.Escape(regexSearch)));
            return r.Replace(path, "");
        }
    }
    }

I am using a version of this library compiled through files I downloaded in a zip through the project page. If there is something wrong with downloading zips, please notify me of the correct way to download and compile this project.

**Comment by Zyano** [comment]
To my knowledge this is issue appears because Youtube have decided to split the audio and video into two different streams. However this change appears to only affect certain resolutions and formats namely things above 360p and in my testing the issue have been very common with webm format in 1080p. 

I haven't found a work around for this yet and it's possible that there aren't one besides of combining the two stream inside C#.
