### ISSUE TITLE
This app don't support on universal.

### ISSUE THREAD

**Issue by Englbach** [flagbug/YoutubeExtractor#127]
On universal don't support .NET. How fix

**Comment by UngarMax** [comment]
Why wouldn't it work? It's just a C# library, nothing more than that.

**Comment by Englbach** [comment]
On universal of VS 2015 RC don't support .Net for Mytoolkip and youtubeExtractor. It will show " system.NET" not loaded....

**Comment by Englbach** [comment]
Could not load file or assembly 'system.net, version=2.0.5.0' on VS2015 RC universal

**Comment by tariqalkhassa** [comment]
you need to use YoutubeExtractor_Portable
it's working for universal apps
