### ISSUE TITLE
404 Forbidden Error

### ISSUE THREAD

**Issue by e4stwood** [flagbug/YoutubeExtractor#129]
when trying to video or audio download a song e.g http(s)://www.youtube.com/watch?v=_IrQHeDcMi8. Get a 404 Forbidden error. 

This even occurs when I strip it all back and just use the sample code.

Cheers!

**Comment by Zyano** [comment]
I'm currently receiving 403 forbidden message when I try to use the library. though I'm not 100% sure it appears that google have made some changes to the URL from which the videos are loaded.

**Comment by tariqalkhassa** [comment]
Solved the problem
change DownloadUrlResolver at your solution to this one and tell me about the results:

https://github.com/tariqalkhassa/YoutubeExtractor/blob/master/YoutubeExtractor/YoutubeExtractor/DownloadUrlResolver.cs

**Comment by Cyano** [comment]
Working for me tariqalkhassa,

Thank you.

**Comment by e4stwood** [comment]
How exactly do I change it? I have found it. Just cant find edit? - http://gyazo.com/29346d1282f25a5d9d8a8de46ad30435

**Comment by e4stwood** [comment]
Okay so it works but it now says there are illegal characters in the path.

Whenever I extract audio, not sure about video.

**Comment by ExoKalork** [comment]
'string' does not contain a definition for 'IsNullOrWhiteSpace'

My .Net version is the latest.

**Comment by Zyano** [comment]
Shouldn't this fix get merged into the repository?

**Comment by tariqalkhassa** [comment]
I tried the code with multiple urls but didn't get this exception
can you give me an example to try to find the error?

**Comment by tariqalkhassa** [comment]
I checked the code and found that the problem was with the VideoInfo objects with no title
after checking the code I found that the problem is because of GetVideoInfos method at DownloadUrlResolver class.
So I made a change at the method and you can find it in here now:
https://github.com/tariqalkhassa/YoutubeExtractor/blob/master/YoutubeExtractor/YoutubeExtractor/DownloadUrlResolver.cs

**Comment by tariqalkhassa** [comment]
@Zyano would you guide me please to merge the changes to the repository? Couldn't find the way to do it

**Comment by Zyano** [comment]
All you can do (to my knowledge) is make a pull request and hope that the owner/administrators of the repository wants to pull/merge those changes into the repository. 
Sorry that I can't be of any more help i haven't really used those features

**Comment by defiler007** [comment]
@ExoKalork use the net framework version 4.0 or above to compile YoutubeExtractor, this worked for me. YoutubeExtractor uses framework 3.5 by default.

**Comment by e4stwood** [comment]
@tariqalkhassa - Your code is throwing - " An exception of type 'System.ArgumentException' occurred in mscorlib.dll but was not handled in user code

Additional information: Illegal characters in path. "

at - this.fileStream = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.Read, 64 * 1024);

Worked before apart from the 404 error!

**Comment by e4stwood** [comment]
Ignore the above. Clearly there was something wrong with the link. Works flawlessly. Thank you!

**Comment by CenturionYun** [comment]
@tariqalkhassa, i tried your branch yesterday night, it work fine. But today it cannot work. The same 403 forbidden issue. Did google changed the algorithm? Can you fix this?

**Comment by CenturionYun** [comment]
@tariqalkhassa, i have tried again, your branch work fine. I need to open VPN. It's awesome. :)
