### ISSUE TITLE
ArgumentNullException on calling DownloadUrlResolver.GetDownloadUrls

### ISSUE THREAD

**Issue by bbougot** [flagbug/YoutubeExtractor#130]
I'm having a ArgumentNullException when passing a YT url as a param to DownloadUrlResolver.GetDownloadUrls. 

![sans-titre-1](https://cloud.githubusercontent.com/assets/8962802/8860985/ba7e31e6-3187-11e5-8132-dbc2ce24cdb9.jpg)

The url syntax is OK (http://www.youtube.com/watch?v=dFQS8IKrUHA) and the exception occurs with any Youtube link. It seems the problem comes from HttpHelper.DownloadString calling :

using (var client = new WebClient())
{
           client.Encoding = System.Text.Encoding.UTF8;
           return client.DownloadString(url);
}

Every Youtube request using client.DownloadString(url) results in a ArgumentNullException exception.

**Comment by tariqalkhassa** [comment]
try to replace the code at DownloadUrlResolver.cs with this one:

https://github.com/tariqalkhassa/YoutubeExtractor/blob/master/YoutubeExtractor/YoutubeExtractor/DownloadUrlResolver.cs

**Comment by e4stwood** [comment]
@tariqalkhassa it seems as though your code throws out a path with invalid characters. (Thats the error I'm now getting!!)

**Comment by tariqalkhassa** [comment]
I tried the code with multiple urls but didn't get this exception
can you give me an example to try to find the error?

**Comment by bbougot** [comment]
I retried this morning and everything's alright, with both original and tariqalkhassa's codes. It may have been a temporary connection issue to Youtube.

**Comment by tariqalkhassa** [comment]
https://github.com/tariqalkhassa/YoutubeExtractor/blob/master/YoutubeExtractor/YoutubeExtractor/DownloadUrlResolver.cs

**Comment by tariqalkhassa** [comment]
I checked the code and found that the problem was with the VideoInfo objects with no title
after checking the code I found that the problem is because of GetVideoInfos method at DownloadUrlResolver class.
So I made a change at the method and you can find it in here now:
https://github.com/tariqalkhassa/YoutubeExtractor/blob/master/YoutubeExtractor/YoutubeExtractor/DownloadUrlResolver.cs
