### ISSUE TITLE
Still getting 403 error on some videos with latest nuget package

### ISSUE THREAD

**Issue by cooldudsk** [flagbug/YoutubeExtractor#132]
With the latest nuget package, audiodownloader still throws a 403 on some videos. I saw some closed issues with a code fix, but I cant edit the new get package, and when I open the zip with visual studio, it is full of errors, especially the isnullorwhitespace

**Comment by defiler007** [comment]
Upgrade the project to .NET Framework 4.0 and the isnullorwhitespace will work!

**Comment by flagbug** [comment]
Should be fixed with https://github.com/flagbug/YoutubeExtractor/pull/151
