### ISSUE TITLE
CanExtractAudio is false for all 17 IEnumerable<VideoInfo> for this vid, why?

### ISSUE THREAD

**Issue by jphellemons** [flagbug/YoutubeExtractor#133]
CanExtractAudio is false for all 17 IEnumerable<VideoInfo> for this vid, why? https://youtu.be/Zg0vgeSb2h0
Looking forward to be able to download this as mp3. All other video's work, it is specific for this one.

Edit: tried again, and works now?

**Comment by Greek6** [comment]
Same here... but for every video

**Comment by ExoKalork** [comment]
Same here

**Comment by GAMELASTER** [comment]
Same here, but still, downloading and extracting audio works. And, i though for all types are all 22 khz bitrate..

**Comment by bassebaba** [comment]
It's quite simple, just check the source code:

public bool CanExtractAudio  { get { return this.VideoType == VideoType.Flash; }   }

So only flash is extractable... 
Guess this might be a problem if (when?) yotube completely drops their flashsupport.

**Comment by jphellemons** [comment]
Perhaps it is easier when the mp4 contains an mp3: http://stackoverflow.com/questions/10633479/how-to-get-sound-portion-of-an-mp4-video-file

**Comment by Greek6** [comment]
Hi,
I'm using MediaToolkit from Nuget, it's super awesome.

Here some snippets:

```
IEnumerable<VideoInfo> videoInfos = DownloadUrlResolver.GetDownloadUrls(youtubeFile.Url);
video = videoInfos.First(info => info.VideoType == VideoType.Mp4); // youtube gives always mp4
if (video.RequiresDecryption)
{
    DownloadUrlResolver.DecryptDownloadUrl(video);
}

var videoDownloader = new VideoDownloader(video, Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop) + "/Downloaded", fileName + video.AudioExtension));

videoDownloader.Execute();

// Convert to mp4 to mp3
// -------------------
var inputFile = new MediaFile { Filename = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop) + "/Downloaded", fileName + video.AudioExtension) };
var outputFile = new MediaFile { Filename = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop) + "/Downloaded", fileName + ".mp3") };

using (var engine = new Engine())
{
      engine.GetMetadata(inputFile);
      engine.Convert(inputFile, outputFile);
}
```
thats it

**Comment by flagbug** [comment]
YoutubeExtractor can only extract the audio track from Flash videos and this won't change in the future, so you'll have to use something like FFMPEG to get this to work, sorry!
