### ISSUE TITLE
Could not parse the Youtube page for URL

### ISSUE THREAD

**Issue by cdanielmarques** [flagbug/YoutubeExtractor#136]
Downloaded the last version, compiled portable version and added to Windows Phone 8.1 project and i'm getting the error:
"Could not parse the Youtube page for url. This may be due to a change of the Youtube page structure".
Tried the modifications in issue #119, with no success.
I'm also receiving the same error using NuGet package.

**Comment by flagbug** [comment]
Should be fixed with https://github.com/flagbug/YoutubeExtractor/pull/151
