### ISSUE TITLE
download youtube playlist

### ISSUE THREAD

**Issue by EdsonAlcala** [flagbug/YoutubeExtractor#141]
would it be nice if you can download a whole playlist from youtube

**Comment by Kimmax** [comment]
**Hey there!**
The YoutubeExtractor gives you the ability to download Videos from YouTube and playlist are only "link holders" which you can use in your application using the YoutubeDataApi. Without wanting to self promote me you can have a look at my repo where I exactly do what you want: [See this file](https://github.com/Kimmax/SYMM/blob/master/src/SYMM%20Backend/YoutubeAPIHandler.cs).

The way you have to go is 
1. Collect the video links from the playlist 
2. Download them one by one

Also here is a short version of what you want in C# using the YouTubeDataAPI:
```C#
// Create playlist request
PlaylistItemsResource.ListRequest playlistVideoRequest = YouTubeService.PlaylistItems.List("snippet,id"); // You can save api calls when you let out snippet, id will be included in the playlisitem itself, however snippet includes more useful information
playlistVideoRequest .PlaylistId = playlistID;
playlistVideoRequest .MaxResults = 50; // If you want to handle playlist with more than 50 items you have to work with page tokens, see linked file above for example how you could handle this.
PlaylistItemListResponse playlistVideoResponse = playlistVideoRequest .Execute();

// We got our respone
foreach (PlaylistItem videoItem in playlistVideosRes.Items)
{
  // You can find the video id in videoItem.Snippet.ResourceId.VideoId, append the id to youtube.com/watch?v= and use this link to download the video
}
```
