### ISSUE TITLE
Parsing   youtube with  HTML5 player

### ISSUE THREAD

**Issue by moiseyo** [flagbug/YoutubeExtractor#142]
I have found that pages 
http://www.youtube.com/watch?v=xAx8Uhs-MjE	
http://www.youtube.com/watch?v=NSBGBBtLmwU
http://www.youtube.com/watch?v=fRf8rY-dMIY

have HTML 5 player and do not parse with current parser

Hoe that can be  fixed 

the problem  in 
     private static JObject LoadJson(string url){
      var dataRegex = new Regex(@"ytplayer\.config\s*=\s*(\{.+?\});", RegexOptions.Multiline);

       string extractedJson = dataRegex.Match(pageSource).Result("$1");

**Comment by flagbug** [comment]
Should be fixed with https://github.com/flagbug/YoutubeExtractor/pull/151
