### ISSUE TITLE
Could not parse the Youtube page for URL http://youtube.com/watch?v=Vd4iNPuRlx4

### ISSUE THREAD

**Issue by chandresh29** [flagbug/YoutubeExtractor#146]
I am developing an app in Unversal and I am getting this error in Windows Phone 8.1 only. for Windows 8.1 it's working properly. Can anyone help me to resolve it.?

Could not parse the Youtube page for URL http://youtube.com/watch?v=Vd4iNPuRlx4

This may be due to a change of the Youtube page structure.

Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues

**Comment by Ownie** [comment]
I'm having the same issue.

**Comment by flagbug** [comment]
Should be fixed with https://github.com/flagbug/YoutubeExtractor/pull/151
