### ISSUE TITLE
Only downloading audio with 64 bitrate

### ISSUE THREAD

**Issue by brco900033** [flagbug/YoutubeExtractor#148]
When I use the audio extraction feature it only downloads the audio with a 64 bitrate (also when the available bitrate(s) is more/less). So how would I fix this? It would be great if I could specify what bitrate should be downloaded.

Thanks in advance

**Comment by DarkN3ss61** [comment]
I am having this same problem

**Comment by flagbug** [comment]
The audio extraction can only extract Flash videos, which have a very low quality audio channel. You have to implement extraction for different formats for yourself.

**Comment by DarkN3ss61** [comment]
Using this website http://keepvid.com/ , it can get it at 128 kbps with the direct link 

http://r2---sn-q4f7sn7s.googlevideo.com/videoplayback?source=youtube&ms=au&pl=40&mv=m&ipbits=0&id=o-AOGjtVuoOg2PVXh6PneZ1rG3W1DH8OIzcj4NahtH_M7t&expire=1447812853&mm=31&clen=2858295&ip=2a03%3A8180%3A1001%3A16a%3A%3A8ee1&dur=179.931&lmt=1446575625932312&fexp=9407610%2C9408710%2C9414764%2C9416126%2C9416556%2C9417683%2C9420453%2C9421765%2C9421932%2C9422428%2C9422596%2C9422618%2C9422918%2C9423428%2C9423510%2C9423639%2C9423662%2C9423714%2C9423791%2C9424082%2C9424372&initcwndbps=9727500&key=yt6&mime=audio%2Fmp4&gir=yes&nh=IgpwcjA1LmRmdzA2KgkxMjcuMC4wLjE&mt=1447791126&keepalive=yes&upn=PqF6YurRmV4&itag=140&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Csource%2Cupn%2Cexpire&signature=63EA3AD5BB356FA7A081CFE74FA83F7DCF592D4B.809D611ED1E4399AEC56BFECE025827DB4960EDF&sver=3&mn=sn-q4f7sn7s&title=CSGO+Tips+with+Na%60Vi+GuardiaN+%7C+In-Game+Roles
