### ISSUE TITLE
Could not parse the Youtube page for URL http://youtube.com/watch?v=knN06v6UGUE

### ISSUE THREAD

**Issue by InVermont** [flagbug/YoutubeExtractor#150]
Could not parse the Youtube page for URL http://youtube.com/watch?v=knN06v6UGUE
This may be due to a change of the Youtube page structure.
Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues

**Comment by di48l069** [comment]
@flagbug @InVermont  Ya same error message looks like youtube has changed something haha

**Comment by di48l069** [comment]
:+1: Legend

**Comment by noammaoz** [comment]
This is solve only part of the problem.
the problem start when trying to DecryptDownloadUrl and it goes to Decipherer.DecipherWithVersion and return null because the base.js is different.

Do you have a solution for this?

**Comment by noammaoz** [comment]
BTW, it require also to change the URL in Decipherer.DecipherWithVersion from:
string jsUrl = string.Format("http://s.ytimg.com/yts/jsbin/html5player-{0}.js", cipherVersion);
to
string jsUrl = string.Format("http://s.ytimg.com/yts/jsbin/player-{0}.js", cipherVersion);

**Comment by Kimmax** [comment]
Apperently my cursor is good at selecting videos that don't need decryption.  
I will look into this when I'm back home. As long as we can read the js file we should be able to fix this.

**Comment by Kimmax** [comment]
Looks like YouTube changed the ciphering more than last time, we'll have to find the code to reverse it in the player js code :-1:

**Comment by noammaoz** [comment]
I have made the following changes and it work for me now:
Class DownloadUrlResolver -> GetHtml5PlayerVersion change from
var regex = new Regex(@"html5player-(.+?)\.js");
to
var regex = new Regex(@"player-(.+?)\.js");

Class Decipherer -> DecipherWithVersion several changes as follows:
string jsUrl = string.Format("http://s.ytimg.com/yts/jsbin/html5player-{0}.js", cipherVersion);
to
string jsUrl = string.Format("http://s.ytimg.com/yts/jsbin/player-{0}.js", cipherVersion);

string funcBodyPattern = @"(?<brace>{([^{}]| ?(brace))*})";
to
//string funcBodyPattern = @"(?<brace>{([^{}]| ?(brace))*})";

string funcPattern = string.Format(@"{0}\(\w+\){1}", @funcName, funcBodyPattern);
to
string funcPattern = @"var " + @funcName + @"=function\(\w+\){.*?};";

var funcBody = Regex.Match(js, funcPattern).Groups["brace"].Value;
to
var funcBody = Regex.Match(js, funcPattern).Value;

for now. this is working well for me on all YouTube video that I have tried.

**Comment by GrabzIt** [comment]
I think it should be:

string funcPattern = @"var " + @funcName + @"=function\(\w+\){.*?};";

**Comment by reincurred-biddle** [comment]
I don't include the source for YouTube Extractor in my solution. Can the developer please update the nuget package to get around this problem? Thanks.

**Comment by MarkOvery** [comment]
+1 on a request for an update to the nuget package.

**Comment by di48l069** [comment]
@InVermont, @noammaoz, @GrabzIt and @reincurred-biddle https://github.com/Kimmax/YoutubeExtractor  is working great just DecryptDownloadUrl is not working i dont think @flagbug is going to update the nuget anytime soon

**Comment by noammaoz** [comment]
@Kimmax YoutubeExtractor is the most updated version?

**Comment by Kimmax** [comment]
To clarify: 
I might be working the most on the extractor, but it isn't extractor only anymore.
I added ffmpeg for the audio extraction (faster, almost all codecs supported) and an audio streamer.
I will implement the fixes from above (Thanks btw) and than my fork should work well.

**Comment by AnonymousUser200102010** [comment]
Does someone have a working version? I'd like to not change my backend yet if at all possible.

No channels don't work at all for me now.

**Comment by waxerjo** [comment]
I'm waiting nuget update.

**Comment by Kimmax** [comment]
i think I got it running again with the code @noammaoz provied, ty!
Although I needed to escape the braces in the regex
```C#
string funcPattern = @"var " + @funcName + @"=function\(\w+\)\{.*?\};";
```
Can someone confirm this working again?
Tested with http://youtube.com/watch?v=knN06v6UGUE and https://www.youtube.com/watch?v=QcIy9NiNbmo

**Comment by di48l069** [comment]
@Kimmax Works great with https://github.com/di48l069/Flash-dl :+1: Create a pull request so @flagbug  can update it. :+1:

**Comment by Kimmax** [comment]
I cant open a pull request for one commit only and my fork has abbreviated too much

**Comment by di48l069** [comment]
True story

**Comment by screamingworld** [comment]
@Kimmax thank you for your fork!

**Comment by ovnisoftware** [comment]
I opened a pull request with Kimmax's fix for this issue.  It has worked for all the links I have tested it with.

**Comment by dragthor** [comment]
@ovnisoftware changes seems to have resolved the issue - https://github.com/flagbug/YoutubeExtractor/pull/151

**Comment by nimobeeren** [comment]
Not familiar with the way these bugfixes are handled with regard to releases, but will we see a NuGet update in the near future?

**Comment by Kimmax** [comment]
Pull request is open, maybe @flagbug just has not enough time. I dropped him a mail asking for push rights here, so I could handle fixes like this in the future. This also includes the nuget.

**Comment by flagbug** [comment]
Hi ya'll, while I don't actively work on this project anymore, I'm still here.

The reason I didn't accept most of the pull requests is, because they either completely changed toe formatting of the source code or added something (in my opinion) completely unnecessary.

I'll review the PR with the parser fix within the next two days and merge it. I'll probably also make some changes to YoutubeExtractor:

I'm probably going to completely remove the logic for video and audio extraction. The only format YoutubeExtractor can currently extract is Flash, which is a format that's basically dead. As an alternative, you can use FFMPEG, which can do wayyy more then just extracting Flash videos.

The video extraction code is written with old .NET 3.5 style, but with .NET 4.5, we're living in an async/await world. I also think that the download of the video should be the responsibility of the user of this library, not the library itself.

**Comment by ovnisoftware** [comment]
In the meantime, here's a temporary fix.  Replace the existing YoutubeExtractor.dll reference in your project with the .dll in this repo.

https://github.com/ovnisoftware/YoutubeExtractor-Fix

**Comment by nimobeeren** [comment]
@ovnisoftware Thank you! I will use your fork with much gratitude while I await a NuGet update.

**Comment by flagbug** [comment]
I've published a new release to NuGet, thanks @Kimmax and all the others!

**Comment by kumkumbum001** [comment]
> Tôi đã xuất bản một bản phát hành mới cho NuGet, cảm ơn @Kimmax và tất cả những người khác!

Can you send me the updated NuGet?
My Email: fungzhangteemo@gmail.com
