### ISSUE TITLE
Getting random 403 forbidden

### ISSUE THREAD

**Issue by DarkN3ss61** [flagbug/YoutubeExtractor#153]
I am getting random 403's with this link
https://www.youtube.com/watch?v=ute-gIa6xlI

Sometimes it will download fine, and other times it crashes telling me 403 forbidden

**Comment by flagbug** [comment]
Which version are you using?

**Comment by DarkN3ss61** [comment]
The latest one you just updated

**Comment by Kimmax** [comment]
@flagbug I wish I could help, but I'm in germany, so I'm gema blocked anyway. I did not experience any 403's lately, but I did before we fixed the cipher. So there may be some condition where we can't decipher the key.
I will do some tunneling later and try out why this won't work sometimes.

**Comment by Kimmax** [comment]
I tried but can't reproduce, sry.

**Comment by dannycarrera** [comment]
I am having this issue as well. Using the latest version. It's happening on all videos.

**Comment by morefun0302** [comment]
https://www.youtube.com/watch?v=bM84aZ0NGZk
this one got 403 error

**Comment by DarkN3ss61** [comment]
I was going to say close this since I was the only one having this issue, but now there are more people

**Comment by morefun0302** [comment]
i think youtube has changed something, coz I did not get 403 with the linklast month, just found the 403 error recently

**Comment by Kimmax** [comment]
I would love to help, but since I'm from germany this video is blcoked by gema for me, tunneling could add unexpected parameters to this situation, so I'm not really able to examine the problem.
However the first thing we need to find is a pattern. There's no random in computers :D

**Comment by dannycarrera** [comment]
Updating to version 0.10.10 fixed it for me. Just an FYI.
