### ISSUE TITLE
Video downloaded  without  sound

### ISSUE THREAD

**Issue by moiseyo** [flagbug/YoutubeExtractor#163]
Thank you fot HTML5 fix , I have now problem  with a few links I can download  video fine with good quality by no sound track  

sample  Links :
https://www.youtube.com/watch?v=ZNZkUt0ePas
https://www.youtube.com/watch?v=GyfgsOO20jU

**Comment by flagbug** [comment]
Duplicate of https://github.com/flagbug/YoutubeExtractor/issues/78
