### ISSUE TITLE
Cannot download from this url

### ISSUE THREAD

**Issue by TixoRebel** [flagbug/YoutubeExtractor#174]
https://www.youtube.com/watch?v=gMBkld5jB0o

**Comment by Zyano** [comment]
I have no problem downloading the video you linked. Can you be more specific about what's wrong when it's downloading?

**Comment by TixoRebel** [comment]
Welp, it works now, it was failing yesterday, now this https://www.youtube.com/watch?v=TiFlMspJvN0 one fails, I pass the download URL to NAudio to use as an audio source, it throws access denied. I've confirmed it's not an issue with NAudio.

**Comment by Zyano** [comment]
I just tried to download that song as well and converting it with ffmpeg and it ran through without any issues. I haven't worked with NAudio before so I'm unaware of how it works, but access denied could be happen if the youtube extractor library is still holding the file on the disk when the conversion begins, but without a more detailed error message then there isn't a whole lot I can do.

**Comment by TixoRebel** [comment]
Alright, what I'm doing is using your API to get a direct link to a video and then using NAudio to pass it through to a Discord (chat service) bot without saving it to file.

**Comment by Gennady-G** [comment]
> https://www.youtube.com/watch?v=gMBkld5jB0o

> https://www.youtube.com/watch?v=TiFlMspJvN0

Both works for me

**Comment by greenjack90** [comment]
I try with "AudioExtract" but "Execute" make me a Exception:
An unhandled exception of type 'System.Net.WebException' occurred in System.dll
Additional information: Errore del server remoto: (403) Non consentito. => (in English "Error with Remote Server, Access Denied")

**Comment by mysteryx93** [comment]
This one fails for me
https://www.youtube.com/watch?v=pOmTdFpIDX8
