### ISSUE TITLE
Unable to find the video with higher quality.

### ISSUE THREAD

**Issue by ElektroStudios** [flagbug/YoutubeExtractor#178]
Taking this example url: [https://www.youtube.com/watch?v=6ONeMhArW5E](https://www.youtube.com/watch?v=6ONeMhArW5E)

The higher quality is an MP4 of 480p, but using the **AudioDownloader** Class it gets a poor video of 240p and a mp3 of very poor quality in 64 kbps:

```
Dim video As VideoInfo = (From vidInfo As VideoInfo In videoInfos
                          Where vidInfo.CanExtractAudio = True
                          Order By vidInfo.AudioBitrate Descending).First
```

I just would like to download the video, as is, (like **JDownloader** does for example) with the higher quality possible containing the audio stream,
but this returns an empty collection:

```
Dim video As VideoInfo = (From vidInfo As VideoInfo In videoInfos
                          Where vidInfo.CanExtractAudio = True
                          Where vidInfo.VideoType = VideoType.Mp4
                          Order By vidInfo.Resolution Descending).First
```
And if I use the **VideoDownloader** Class with this LINQ query then it just downloads the video stream with the higher quality but with no audio stream inside:

```
Dim video As VideoInfo = (From vidInfo As VideoInfo In videoInfos
                          Where vidInfo.VideoType = VideoType.Mp4
                          Order By vidInfo.Resolution Descending).First
```

If this is not possible with **YoutubeExtractor** (because seems discontinued and incompeted), is there any other good library for .Net developers that can properly handle video resolutions/audio-bitrates?.

**Comment by flagbug** [comment]
As stated in the README, YoutubeExtractor support `audio extraction currently only for flash videos`

If you want to download the audio track with a higher quality, just use the download link of the video info and pass it into a `HttpClient`

**Comment by flagbug** [comment]
> And if I use the VideoDownloader Class with this LINQ query then it just downloads the video stream with the higher quality but with no audio stream inside:

This is because Youtube splits the audio and video tracks. See #78

**Comment by ElektroStudios** [comment]
Thankyou so much!
