### ISSUE TITLE
System.Net.WebException: The remote server returned an error: (403) Forbidden

### ISSUE THREAD

**Issue by MikeGitIt** [flagbug/YoutubeExtractor#181]
I am seeing this error consistently now. Assuming YouTube has changed something which blocks non-browser access? Either way, I am putting this here as a placeholder in case others see the same issue.   I will continue to troubleshoot the issue, as time permits, and report my findings, if any, once I am done.

**Comment by alexsychev** [comment]
The same issue. Any ideas?

**Comment by ovnisoftware** [comment]
Have you tried downloading from a different IP address?  I get a System.Net.WebException error if I try to download videos that are restricted to certain countries like for example this one: https://www.youtube.com/watch?v=pC6ZMPUUzsM

**Comment by MikeGitIt** [comment]
It was a firewall issue. I'm good, sorry. I should've updated the post.

On Sunday, May 29, 2016, ovnisoftware <notifications@github.com> wrote:

> Have you tried downloading from a different IP address? I get a
> System.Net.WebException error if I try to download videos that are
> restricted to certain countries like for example this one:
> https://www.youtube.com/watch?v=pC6ZMPUUzsM
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/flagbug/YoutubeExtractor/issues/181#issuecomment-222385150>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACBvWNSwnGcHnBoDLtZ3bj2HPDFEtQP_ks5qGgubgaJpZM4H9sE->
> .
>


-- 
Michael Latham,
Senior Software Engineer
mlatham74@gmail.com
803-445-5110
