### ISSUE TITLE
VideoDownloader class not recognized in UWP app

### ISSUE THREAD

**Issue by touseefbsb** [flagbug/YoutubeExtractor#182]
i am building a UWP app and i tried using this library, and pasted the sample example code provided, all other code lines show no compile errors, but videodownloader class, is not being recognized by the compiler

**Comment by flagbug** [comment]
The `AudioDownloader` and `VideoDownloader` classes aren't supported in the PCL profile

**Comment by touseefbsb** [comment]
so does that mean this library cannot be used in UWP projects?

**Comment by flagbug** [comment]
No, it just means that the `AudioDownloader` and `VideoDownloader` classes can't be used in UWP projects
