### ISSUE TITLE
Bad request 403 forbidden

### ISSUE THREAD

**Issue by torsten2** [flagbug/YoutubeExtractor#194]
Decrypted videos can't be downloaded anymore. VideoDownloader throws.

Example url https://www.youtube.com/watch?v=OPARVXqrbWc

**Comment by torsten2** [comment]
https://r8---sn-qu5b-q0ne.googlevideo.com/videoplayback?ip=79.221.113.232&upn=FE-CbQv3gzU&itag=36&dur=216.084&lmt=1464869427930507&fexp=9405975,9416126,9416891,9422596,9422841,9424333,9428398,9429264,9431012,9432182,9432366,9432565,9433096,9433380,9433946,9435526,9435695,9435876,9436633,9436802,9436910,9437066,9437553,9438336,9438762,9438765,9438805,9439363,9439580,9439652,9440014&sparams=dur,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,upn,expire&sver=3&source=youtube&mt=1466757710&mime=video/3gpp&ipbits=0&initcwndbps=1052500&mv=m&pl=24&mn=sn-qu5b-q0ne&requiressl=yes&ms=au&mm=31&expire=1466779489&key=yt6&id=o-ABOZp7dO7EOqbebM1OXWE74eWxhjyEhlNDmVWZ_0FZop&signature=5C4EB7344F0151C52C6E9EE738FAC2EDD1D1D879.652DBA517B272CBA6D3921ABFF1E730774E76F58&ratebypass=yes

http://r8---sn-qu5b-q0ne.googlevideo.com/videoplayback?fexp=9407015%2C9413209%2C9414823%2C9416126%2C9416891%2C9419452%2C9422596%2C9428398%2C9431012%2C9431718%2C9432049%2C9433096%2C9433223%2C9433946%2C9435526%2C9435666%2C9435693%2C9435699%2C9435876%2C9435958%2C9436015%2C9436345%2C9437066%2C9437228%2C9437553%2C9437742%2C9438789%2C9439585%2C9439652&keepalive=yes&pl=24&itag=134&mime=video%2Fmp4&clen=8932164&gir=yes&id=o-ALQT_jjNcn_lm1fUgdugk_27actS6BAzHj83nFMF1WHP&source=youtube&dur=216.000&expire=1466779569&key=cms1&ip=79.221.113.232&lmt=1465018003796990&sver=3&upn=ZROGQ8hnoEc&ipbits=0&sparams=clen,dur,expire,gir,id,initcwndbps,ip,ipbits,ipbypass,itag,keepalive,lmt,mime,mm,mn,ms,mv,nh,pl,source,upn&signature=7132E322D27AC5592E8D19C8FCD02611F1362286.3D99C593C583B0AD72C567B39BCED1131CF8B7D8&title=Farid+Bang+feat.+18Karat+%E2%96%BA+KOMA+REMIX+%E2%97%84+%5B+official+Video+%5D+4K+prod.+by+Joshimixu+%26+Bad+Educated&redirect_counter=1&req_id=8fd5a991c7d6a3ee&cms_redirect=yes&ipbypass=yes&mm=31&mn=sn-qu5b-q0ne&ms=au&mt=1466757710&mv=m

**Comment by torsten2** [comment]
Second one works. Its from keepvid. First one is our.

**Comment by nguyendinhhop** [comment]
Same issue, can't download any Vevo video

**Comment by torsten2** [comment]
Its so strange ... Sometimes it works with decrypted ones and sometimes not!?

**Comment by nguyendinhhop** [comment]
Change 
`var funcPattern = @"" + @funcName + @"=function\(\w+\){.*\n?.*};";`
to
`var funcPattern = @"(?!h\.)" + @funcName + @"=function\(\w+\)\{.*?\}";`

**Comment by darksody** [comment]
Thank you kind sir! I've been waiting for this. I was using the MyToolkit.Extended, but that broke as well. Now using the youtube extractor :)

**Comment by Kimmax** [comment]
This is what #195 fixes, also there is sometimes a issue with the correct signature length, so you may want to cover this aswell
