### ISSUE TITLE
Extract Audio issue

### ISSUE THREAD

**Issue by noammaoz** [flagbug/YoutubeExtractor#196]
The following code return exception because there is no CanExtracAudio in the videoInfos:
`VideoInfo video = videoInfos
                .Where(info => info.CanExtractAudio)
                .OrderByDescending(info => info.AudioBitrate)
                .First();`

Is there any solution for this? how can I extract action from the video?

**Comment by LinPolly** [comment]
You can use it temporarily, but it is downloaded MP4, it is audio only.
`new VideoInfo(140, VideoType.Mp4, 0, false, AudioType.Aac, 128, AdaptiveType.Audio),`

Method is equivalent to download videos
`VideoInfo video = videoInfos.First(info => info.VideoType == VideoType.Mp4 && info.Resolution == 0);`

English grammar questions, please forgive me, these are the translation in Google.

**Comment by noammaoz** [comment]
If I will do this, I don't need anymore the flv file extraction stream function.
I will need to change the AudioDownloader.cs file for this.

**Comment by LinPolly** [comment]
Just use VideoDownloader.cs, and AudioDownloader.cs not use.

But out of the downloaded files in detail the audiobitrate = 0, it is actually closer to 128.

You can manually change the file extension or directly specified by the program file extension ".mp3", but this will be the audiobitrate = null.

When you download 480p, 1080p, 1440p, 2160p is not these audio files, if you download the video first and then download the audio, you can use ffmpeg video and audio synthesis. This way your 480p, 1080p, 1440p, 2160p is to have the audiobitrate = 128 audio and video files.

**Comment by noammaoz** [comment]
I have download the MP4 audio file which is AAC\M4A file so I have stream object of it. I there way to convert it to MP3?
I have tried NReco.VideoConverter (ConvertLiveMedia) and the result is empty object.

**Comment by LinPolly** [comment]
If you download only the audio files. I want to manually change the file extension to ".mp3" because this is also possible.
or
`var videoDownloader = new VideoDownloader(video,
                                    Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop),
                                    RemoveIllegalPathCharacters(video.Title) + ".mp3"));`

**Comment by noammaoz** [comment]
I think you misunderstand my question. I have use the video info of AdaptiveType.Audio and VideoType.Mp4 and I performed response.GetResponseStream so I'm getting stream object with the MP4 audio file. Now I want to convert the stream object to MP3 without saving it on the disk.
Do you know how a way to convert MP4\M4A to MP3?

**Comment by Nulifyer** [comment]
i also have this issue , you cant use the method in the example to download audio the only method i have is to download 720p video and extract audio from the mp4 file.  please let me know if there is a better way, one that is simpler.

**Comment by Singuini** [comment]
The AudioDownloader class (or atleast the audio extraction part of it) has been completely useless for a long period of time now, is anything being done to fix or improve it? If not, can someone with the proper knowledge please do something? :)
I mean, the ability to download audio-files is after all one of the most important features in this library.

In the meantime, please share any alternative solutions for downloading mp3's from youtube.
I'm so fed up with having to create fake mp3's out of "resolutionless mp4's explicitly converted into mp3".

**Comment by flagbug** [comment]
> The AudioDownloader class (or atleast the audio extraction part of it) has been completely useless for a long period of time now, is anything being done to fix or improve it?

No, stop using it.

**Comment by jphellemons** [comment]
if it does not work anymore, perhaps remove it and update the nuget?

**Comment by noammaoz** [comment]
I have found a solution for this issue:
I have changed the VideoInfos selection to:
this.Video = videoInfos
                .Where(info => info.AudioBitrate > 0 && info.AdaptiveType == AdaptiveType.Audio)
                .OrderByDescending(info => info.AudioBitrate).First();

In the Execute method I'm downloading the file (which is MP4/AAC) and convert is to MP3 with NReco.VideoConverter.FFMpegConverter
