### ISSUE TITLE
No audio in 1080p videos?

### ISSUE THREAD

**Issue by cmdr2** [flagbug/YoutubeExtractor#202]
Hi there,

Video urls with 1080p (and higher) don't appear to have an audio track in them. For e.g. https://www.youtube.com/watch?v=t99N223fqCo

I downloaded the latest version (as of today) of YoutubeExtractor.

Here's the code snippet:

		string link = "https://www.youtube.com/watch?v=t99N223fqCo";
		IEnumerable<VideoInfo> videoInfos = DownloadUrlResolver.GetDownloadUrls(link);

		VideoInfo video = videoInfos
			.First(info => info.VideoType == VideoType.Mp4 && info.Resolution == 1080);
		
		print ("Before decr: " + video.DownloadUrl);
		if (video.RequiresDecryption)
		{
			DownloadUrlResolver.DecryptDownloadUrl(video);
		}

		print("After decr: " + video.DownloadUrl);

Changing the resolution to 720 or 360 works however (i.e. the audio is present).

Is there something I'm missing?

Cheers
~cmdr2

**Comment by cmdr2** [comment]
Although poking around a bit, I doubt there's a straightforward solution, since the raw URLs in the JSON on the youtube page don't have audio either, so I assume the YouTube player synchronizes separate audio and video tracks.

**Comment by flagbug** [comment]
See #78
