### ISSUE TITLE
Portable library

### ISSUE THREAD

**Issue by xamarin-volkan** [flagbug/YoutubeExtractor#206]
kindly ask you to make a portable version for Xamarin Forms.
like https://github.com/famoser/YoutubeExtractor.Portable

**Comment by flagbug** [comment]
This library is already portable...

**Comment by xamarin-volkan** [comment]
Great. If I did not miss it, may be you can mention it, somewhere.

**Comment by flagbug** [comment]
@xamarin-volkan https://github.com/flagbug/YoutubeExtractor#target-platforms

**Comment by trollicode** [comment]
some youtube video are not downloadable by using YoutubeExtrator Code in xamain forms. 
this link is not generate download url. check out: 
https://www.youtube.com/watch?v=_Fwf45pIAtM
