### ISSUE TITLE
How to find highest available youtube resolution?

### ISSUE THREAD

**Issue by theluthfi** [flagbug/YoutubeExtractor#214]
`VideoInfo video = videoModel.VideoInfo.First(info => info.VideoType == VideoType.Mp4 && info.Resolution == 360);`

 I was looking for something like if 1080 doesnt exist then look for 720, if that doesnt exist then look for 480.

**Comment by Gennady-G** [comment]
It is good idea

**Comment by hlgbls** [comment]
var video = videoInfos.OrderByDescending(info => info.Resolution).First(info => info.VideoType == VideoType.Mp4);

Something like this.

**Comment by theluthfi** [comment]
Finally, this is works fine for me


public static IEnumerable<VideoInfo> GetVideoInfos(YoutubeModel model)
{
    int xx;
    IEnumerable<VideoInfo> videoInfos = DownloadUrlResolver.GetDownloadUrls(model.Link);

        int[] arr = new int[3] { 360, 720, 1080 };
        for (xx = 0; xx < 3; xx++)
        {
            try 
            {
                VideoInfo video = videoInfos
                                   .First(info => info.VideoType == VideoType.Mp4 && info.Resolution == arr[xx]);
            }
            catch (Exception st)
            {

            }
        }
    return videoInfos;
}

//Returns VideoInfo object (Only for video model)
public static VideoInfo GetVideoInfo(YoutubeVideoModel videoModel)
{
    //Select the first .mp4 video with 360p resolution
    VideoInfo video = videoModel.VideoInfo.First();
    return video;
}

**Comment by SriramSakthivel** [comment]
@theluthfi Sort the VideoInfos by descending order based on resolution then pick the first one.

**Comment by vankyy26** [comment]
VideoInfo video = videoModel.VideoInfo.OrderByDescending(ob=> ob.Resolution).First();

**Comment by bpetersen1** [comment]
This is what i did, kinda similar to the others.

 private static VideoInfo SortedYoutubeObject(IEnumerable<VideoInfo> v)
        {
            //From the list of video's, find the quality of video the user wants based on the value from the config
            var video = v
                .FirstOrDefault(
                    info => (info.VideoType == VideoType.Mp4) && (info.Resolution == Configs.VideoResolution));

            //If no youtube video is found with the quality that the user wants, select the best quality from the list
            if (video == null)
            {
                video = v
                    .OrderByDescending(x => x.Resolution)
                    .First(info => info.VideoType == VideoType.Mp4);

                SystemMessage.WriteConsoleMessage(
                    $"{Environment.NewLine}Could not find a {Configs.VideoResolution}p version of the video you where looking for. Downloading a {video.Resolution}p version {Environment.NewLine}",
                    ColorEnum.Yellow, false, false);
            }
            return video;
        }

**Comment by bpetersen1** [comment]
dont use .First(), it might throw an exception
