### ISSUE TITLE
Forbidden (403)

### ISSUE THREAD

**Issue by SomeOneMore** [flagbug/YoutubeExtractor#228]
From some hours ago, the extractor is not running.
Got 403 error in each download.
Any solution to this?
Regards

**Comment by LinPolly** [comment]
> https://github.com/rg3/youtube-dl/pull/11892/files

I refer to from youtube-dl # 11892 Files changed
Decipherer.cs#L16
`string functNamePattern = @"\.sig\s*\|\|([a-zA-Z0-9\$]+)\("; //Regex Formed To Find Word or DollarSign`
To
`string functNamePattern = @"\""signature"",\s?([a-zA-Z0-9\$]+)\("; //Regex Formed To Find Word or DollarSign`
Working for me

**Comment by SomeOneMore** [comment]
Solved.
Thanks!

**Comment by Kwoth** [comment]
@SomeOneMore How did you solve it? Compiled the library yourself with the fix? Can you show us the line you've edited if you did?

**Comment by SomeOneMore** [comment]
Hi Knowth.
Open the downloaded library project
Open file: Decipherer.cs
Go to line 16
Change the line:
`string functNamePattern = @"\.sig\s*\|\|([a-zA-Z0-9\$]+)\("; //Regex Formed To Find Word or `DollarSign`
by the line:
`string functNamePattern = @"\""signature"",\s?([a-zA-Z0-9\$]+)\(";`
Build the dll.

**Comment by Kwoth** [comment]
Oh i am blind. I've just read the link and ignored the rest of his message. Sorry my bad.

**Comment by iamtorsten** [comment]
This will fix the problem ...

https://github.com/mrklintscher/AVTube/commit/2c44d4ca72ae4bc7810524e596bb98fab2036890
