### ISSUE TITLE
Video download fail (but works with other links)

### ISSUE THREAD

**Issue by mysteryx93** [flagbug/YoutubeExtractor#236]
Download works for other videos, but this one I can't download.
https://www.youtube.com/watch?v=GytW_rgr0RM

**Comment by ghost** [comment]
Ι downloaded succesfully with YoutubeExtractor at 720p. What version you use ? I am using the github version seens the nuget one is "outdated".

**Comment by mysteryx93** [comment]
Will have to debug deeper into the code then to see what's going on...

**Comment by mysteryx93** [comment]
Debugging into it, I get a Forbidden (403) error when the download starts.

The video I'm downloading is 1080p MP4 format code 137. Url:
https://r4---sn-0opoxu-j0oe.googlevideo.com:443/videoplayback?mt=1487204961&mv=m&ms=au&source=youtube&keepalive=yes&mime=video/mp4&clen=70394951&requiressl=yes&mm=31&mn=sn-0opoxu-j0oe&initcwndbps=947500&id=o-ANcxmgcO3fyjoievHLdwlnALFVnnxXkGXLOYC1RcaZFk&ei=ovKkWJicKM-r-wXF3a3gBA&upn=h-sAj4KaYSY&lmt=1458194928992314&ip=189.149.153.171&sparams=clen,dur,ei,gir,id,initcwndbps,ip,ipbits,itag,keepalive,lmt,mime,mm,mn,ms,mv,pcm2cms,pl,requiressl,source,upn,usequic,expire&gir=yes&pl=19&dur=178.845&expire=1487226626&pcm2cms=yes&usequic=no&itag=137&key=yt6&signature=23DAB2F377C779F0E21E131BD9277FEAC2E5F09D.DAC12CE37958C3FEFDC4A3F68264E3D88DDA53&ipbits=0&ratebypass=yes

What's interesting, also, is that this video has no "dashmpd" attribute containing extra formats (the official release doesn't read those formats but my custom build does)

**Comment by mysteryx93** [comment]
I found the problem. I was calling DecryptDownloadUrl even if RequiresDecryption was false.

YouTube is removing encryption from their latest videos.
