### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Xwilarg** [flagbug/YoutubeExtractor#282]
Hi,
I copied the code given as an example but when I launch it I get a WebException "403 Forbidden", but the error doesn't happen every times.
To give an example, it's not working for this video: https://youtu.be/hxSg2Ioz3LM
But it's working for this video: https://youtu.be/8-Epnpruww0
Thanks in advance,

**Comment by Reptarsrage** [comment]
it has to do with the RequiresDecryption flag
