### ISSUE TITLE
Could not parse the Youtube page

### ISSUE THREAD

**Issue by gary-89** [flagbug/YoutubeExtractor#306]
![error 403](https://user-images.githubusercontent.com/4557953/41474285-e21fc5e0-70bb-11e8-8fb9-631652b62cab.png)

> Could not parse the Youtube page for URL http://youtube.com/watch?v=1FExIWex_vc
> This may be due to a change of the Youtube page structure.
> Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues.

What can I do?

I often get a **System.Net.WebException: 403 Forbidden** when I call the _.Execute_ method of VideoDownloader. 

Parsing the error, I've found that the issue may be caused by a missing SSL request (watch the image).

Any help?

**Comment by exit99** [comment]
+1

**Comment by OptixA3** [comment]
I get both of these issues too, only happens on certain videos I've noticed, however. Any fixes for this would be greatly appreciated.

**Comment by gary-89** [comment]
In the end, I've decided to NOT use this library anymore.. It's not working and it is not well maintained.
Instead use: [YoutubeExplode](https://github.com/Tyrrrz/YoutubeExplode)
It works MUCH better
