### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by devnulli** [flagbug/YoutubeExtractor#340]
Hi, 

I was wondering if this project is still maintained, or if there is any fork that's being maintained.

cheers.

**Comment by rcabreu** [comment]
Doesn't look like it. @flagbug

**Comment by devnulli** [comment]
Thanks.

**Comment by anilgit90** [comment]
A fork is maintained https://github.com/anilgit90/YoutubeExtractor with some changes.
