### ISSUE TITLE
youtube uri decipher signature not works

### ISSUE THREAD

**Issue by HFAsif** [flagbug/YoutubeExtractor#358]
the decription not works any more . can some one show the way how we can fix it . @omansak  done that job i saw. 

string jsUrl = string.Format("http://s.ytimg.com/yts/jsbin/player_ias-{0}.js", cipherVersion);

string functNamePattern = (@"\bc\s*&&\sa.set([^,]+,\s(?:encodeURIComponent\s*()?\s*([\w$]+)("); //Regex Formed To Find Word or DollarSign

var funcBody =
Regex.Match(
js,
$@"(?!h.){Regex.Escape(funcName)}=function(\w+){{(.*?)}}",
RegexOptions.Singleline).Value;

it not works in
foreach (var line in lines.Skip(1).Take(lines.Length - 2))

**Comment by omansak** [comment]
Ok i will check that

**Comment by developerss** [comment]
many thank you .

**Comment by developerss** [comment]
if you have done please provide

**Comment by HFAsif** [comment]
> Ok i will check that

is there any progress

**Comment by noammaoz** [comment]
YouTube change something in the signature. the signature is empty, anyone know how to solve this issues?

**Comment by HFAsif** [comment]
i know how to solve it .

**Comment by HFAsif** [comment]
but it not possible with youtube extractor deciper function. you need to create dynamic decryptor to decrypt new encryption . and some changes in regex

**Comment by noammaoz** [comment]
OK, can you share the changes so i can implement it in the c# code?

**Comment by LinPolly** [comment]
This is the regular expression I am currently using, give it a try!!
`string functNamePattern = @"(\w+)\s*=\s*function\(\s*a\s*\)\s*{\s*a\s*=\s*a\.split\(\s*""""\s*\)";`

**Comment by noammaoz** [comment]
This function return exception:
operations.Split(new[] { " " }, StringSplitOptions.RemoveEmptyEntries).Aggregate(cipher, ApplyOperation);

this part of DecipherWithOperations function. The cipher is empty. Even after understand the issue of the signature with the value of "signature=_=_===w=qx3SuUlHftOsJsIHmVFNgkDsUZ3VxZUO7x-sQvcfiBiAnF-xPDZ5PvpaQs77GE3Yrz1LaRgh7E9vAtB4AwzGE-KAhIQRww2IxgLA" there is still exception of The remote server returned an error: (403) Forbidden

**Comment by HFAsif** [comment]
https://github.com/LinPolly/20181114/issues/1

**Comment by noammaoz** [comment]
Thanks a lot. your solution solved the issue.

**Comment by HFAsif** [comment]
please thanks to Linpolly ,

**Comment by kns98** [comment]
Request the author to integrate the fixes as they work.
