### ISSUE TITLE
Unable to use the "percentage-handler" in vb .net

### ISSUE THREAD

**Issue by koztantwo** [flagbug/YoutubeExtractor#74]
I use the YoutubeExtractor and the audio download works very nice. The only problem i have is, that i don't know how to use the "percentage-handler" or how i have to implement it. Do you have any idea?

**Comment by cooldudsk** [comment]
Hi, Im using your code above for the windows forms (although Im using c#) Im not sure where to put this question, but I figures since im using your code, I should put it here. Basically im doing the exact same thing in c# and id like to use audiodownloader instead of videodownloader, but when it gets to AudioDL.Execute(); I get the error: AudioExtractionExceptoin was unhandled Invalid Input file, impossible to extract audio track. Any idea what is causing this?

    public partial class Form1 : Form
      {

        private bool mAllowWorkRestart;

        public AudioDownloader AudioDL;


        public Form1()
        {
            InitializeComponent();
        }


        private void Form1_Load(object sender, EventArgs e)
        {

        }

        private void button1_Click(object sender, EventArgs e)
        {
           
            mAllowWorkRestart = true;

            string webLink = "https://www.youtube.com/watch?v=hPokJFyUq1s";

            IEnumerable<YoutubeExtractor.VideoInfo> videoInfos = default(IEnumerable<YoutubeExtractor.VideoInfo>);

            //You can make this run in the background aswell, but for this example. I'll just the main video download in background

            videoInfos = DownloadUrlResolver.GetDownloadUrls(webLink);

            VideoInfo singleVideo = videoInfos.First();
            //Just using whatever was first for this example
            AudioDL = new AudioDownloader(singleVideo, "C:\\Downloads" + singleVideo.AudioExtension);

  

            
            progressBar1.Value = 0;
            button1.Enabled = false;
            button1.Text = "Downloading...";

            backgroundWorker.RunWorkerAsync();
            //Start background task
        }

        private void downloaderProgressChange(object sender, YoutubeExtractor.ProgressEventArgs e)
        {
            backgroundWorker.ReportProgress(Convert.ToInt32(e.ProgressPercentage));
            //Send the val of download to the worker
        }

        private void backgroundWorker1_DoWork_1(object sender, DoWorkEventArgs e)
        {
            AudioDL.DownloadProgressChanged += downloaderProgressChange;
            AudioDL.Execute();
            //Task runs in background
        }

        private void backgroundWorker1_ProgressChanged(object sender, ProgressChangedEventArgs e)
        {
            progressBar1.Value = e.ProgressPercentage;
            //Change the progressbar value. 
        }

        private void backgroundWorker1_RunWorkerCompleted(object sender, RunWorkerCompletedEventArgs e)
        {
            button1.Text = "Download";
            button1.Enabled = true;
        }


    }
