### ISSUE TITLE
AudioDownloader seems missing for windows phone 8.1

### ISSUE THREAD

**Issue by jphellemons** [flagbug/YoutubeExtractor#81]
Am I missing something?
![screenshot of visual studio](http://i.imgur.com/QMRWPGo.png)

VideoDownloader is also unavailable. What am I missing out on this monday morning?

**Comment by ducthang123** [comment]
please help Am I missing something?
![image](https://cloud.githubusercontent.com/assets/5811045/10601229/328cb1a6-773a-11e5-95da-dfcef4f2d25e.png)

**Comment by ducthang123** [comment]
I have added your YoutubeExtractor from here
![image](https://cloud.githubusercontent.com/assets/5811045/10601406/af7653e2-773b-11e5-8658-1f980ac6b6db.png)
