### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by ijourneaux** [flagbug/YoutubeExtractor#87]
I have been using YouTube Extracker for some time in my project HD-Trailers.net Downloader.
It always works on my computers but I ahve a user you gets the attached error message.
Any idea why this might be happening and what the solution might be?

10/9/2014 11:55:41 AM - ERROR: Problem with youtubeDownloader 
10/9/2014 11:55:41 AM - System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) 
File name: 'Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' 
at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature) 
at HDTrailersNETDownloader.Program.YouTubeDownload(String downloadURL, String fName, String dirName, String qualPref) 

=== Pre-bind state information === 
LOG: DisplayName = Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed 
(Fully-specified) 
LOG: Appbase = file:///C:/Program Files (x86)/HD-Trailers.NET Downloader/ 
LOG: Initial PrivatePath = NULL
Calling assembly : YoutubeExtractor, Version=0.10.4.0, Culture=neutral, PublicKeyToken=null.
LOG: This bind starts in default load context. 
LOG: No application configuration file found. 
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config. 
LOG: Post-policy reference: Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed 
LOG: Attempting download of new URL file:///C:/Program Files (x86)/HD-Trailers.NET Downloader/Newtonsoft.Json.DLL. 
WRN: Comparing the assembly name resulted in the mismatch: Major Version 
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

**Comment by Operator187** [comment]
same  error here, tried all kinds of different things...still havent found a fix

**Comment by ijourneaux** [comment]
I wish I could help but I don't remember exactly how I got past this but I did get past it.

**Comment by GuntaButya** [comment]
Repost: 

I also have had this issue, app been working fine for months, all of a sudden throwing an exception...

I had several different threads working on getting data and also downloading, this seems to be a thread based issue, I moved the line:

IEnumerable videoInfos = DownloadUrlResolver.GetDownloadUrls(link);

To the main thread and its all good, at least that's at the moment. Very strange, my app as had nothing change, an odd problem!

PS: Great Lib, thanks so much for your excellent hard work here!!!

**Comment by GuntaButya** [comment]
I run up a Console Application today as a test, Newtonsoft was not installed/included in the Packages folder.

I had to use Version:   5, 0, 8, 16617 

Newer versions do not work.

**Comment by retro617** [comment]
I was having that issue too.  It kept telling me to use Json 6.0.6 and it kept giving me an error.  What I did was recompile with ALL of the updates and then I added Newton Json 10.0.1.2.  That was this morning and it is working well now.
