### ISSUE TITLE
YouTubeExtractor and Newtonsoft.json

### ISSUE THREAD

**Issue by ijourneaux** [flagbug/YoutubeExtractor#88]
For some reason, when my application calls YouTubeExtractor, I get the following error message. I have tried unstalling and reinstalling YouTubeExtractor (including Newtonsoft.json) and Newtonsoft.json separatly but I still get the error. I have followed some of the suggestions on Stack Exchange (wrt Newtonsoft.json) but none of the solutions seem to work for me.

10/14/2014 10:30:07 AM - YouTube Trailers Download ...
10/14/2014 10:30:07 AM - ERROR: Problem with youtubeDownloader
10/14/2014 10:30:07 AM - System.IO.FileLoadException: Could not load file or ass
embly 'Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe
6b2a6aeed' or one of its dependencies. The located assembly's manifest definitio
n does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30
ad4fe6b2a6aeed'
   at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Bool
ean decryptSignature)
   at HDTrailersNETDownloader.Program.YouTubeDownload(String downloadURL, String
 fName, String dirName, String qualPref)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\M
icrosoft\Fusion!EnableLog](DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure lo
gging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fus
ion!EnableLog].

**Comment by GuntaButya** [comment]
I also have had this issue, app been working fine for months, all of a sudden throwing an exception...

I had several different threads working on getting data and also downloading, this seems to be a thread based issue, I moved the line:

IEnumerable<VideoInfo> videoInfos = DownloadUrlResolver.GetDownloadUrls(link);

To the main thread and its all good, at least that's at the moment. Very strange, my app as had nothing change, an odd problem!
