### ISSUE TITLE
Audio Quality

### ISSUE THREAD

**Issue by DarkTussin** [flagbug/YoutubeExtractor#95]
Hi FlagBug,

I started using your library quite some time ago and I recall the audio being extracted in a different format. Now it seems to only extract .mp3 files at 64kbps (using the example code). When I try downloading the same video from an online site (like flvtomp3), it seems to extract the audio at a much higher bitrate.

Is this a setting I can change in the code or is this a limitation of the extraction library?

Sorry if this is the wrong place to ask, and thanks!

**Comment by flagbug** [comment]
Probably the same issue as https://github.com/flagbug/YoutubeExtractor/issues/92

**Comment by DarkTussin** [comment]
Ahh gotcha; sorry I didn't see that issue when I was looking through them. Assuming I just download the video and try to ffmpeg the audio myself, if I leave out CanExtractAudio, it will still download the full mp4 video with audio, right?

**Comment by flagbug** [comment]
Nope, for some videos, YouTube separates the video and audio tracks (it's called DASH playback, the `VideoInfo` class has the property `AdaptiveType` to check whether it's a video or audio track). 

You'll have to download them both and join them via FFMPEG and friends

**Comment by DarkTussin** [comment]
Hey flagbug, could you give me some info on how do download just the DASH audio file?

**Comment by flagbug** [comment]
Sure, filter for `VideoInfo.AdaptiveType == AdaptiveType.Audio`

**Comment by DarkTussin** [comment]
Once I have the right file, do I run it through VideoDownloader.Execute() instead of AudioDownloader.Execute()?

**Comment by flagbug** [comment]
`VideoDownloader.Execute()`, or $WEBCLIENT

AudioDownloader just extracts the audio file of .flv files, nothing else

**Comment by DarkTussin** [comment]
Thanks again for your help - I guess I'm missing a codec or something for the .aac file on this computer. VLC doesn't want to play it, but it looks like it's probably working.

Last thing, sorry again to bug you with this - can I use Newtonsoft.Json to get the video links from a playlist file? Could you point me in the right direction on how to do this?

Thanks again :)

**Comment by flagbug** [comment]
I think this should work with the [Official YouTube API](https://developers.google.com/api-client-library/dotnet/get_started)

**Comment by DarkTussin** [comment]
Awesome, thank you :)

**Comment by DarkTussin** [comment]
Well, I'm working on this: http://i.imgur.com/KOhdVda.png

So far I have only released the initial build, but I'm almost done: http://recursivehack.com/RainDrop.php

I tried pulling youtube video data using json, but I was getting weird issues, so I ended up just regexing the playlist files ... but now I have to adjust it so I can get over 100 links.

Thanks again for your help
