### ISSUE TITLE
The remote server returned an error (403) Forbidden

### ISSUE THREAD

**Issue by DarkTussin** [flagbug/YoutubeExtractor#97]
Hey flagbug, I had some code that seemed to be working yesterday, but now when I run it is returning (403) Forbidden errors. An example link is:

http://www.youtube.com/watch?v=_FrOQC-zEog

I ran a previous build that was working a couple days ago, but it doesn't seem to be working now.
I was wondering if you were running into the same issue, or if I'm doing something wrong.

In addition, I received this error from this link:

http://youtube.com/watch?v=x-C9GIS_NPc
Could not parse the Youtube page for URL http://youtube.com/watch?v=x-C9GIS_NPc
This may be due to a change of the Youtube page structure.
Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues

Thanks for your time

Here are a few more links if you want some examples:

Forbidden errors:

http://youtube.com/watch?v=EHu98jm7JLs failed to condense.
The remote server returned an error: (403) Forbidden.

http://youtube.com/watch?v=L8ljy0FMox0 failed to condense.
The remote server returned an error: (403) Forbidden.

http://youtube.com/watch?v=zvGNyPv3hfU failed to condense.
The remote server returned an error: (403) Forbidden.

**Comment by Cyano** [comment]
Yeah the latest signature includes a $ sign in the function body.The current regex is formed to find letters and numbers only.
Pretty simple fix, A pull request will go up any minute now so if you can try it out that would be great.

**Comment by DarkTussin** [comment]
Definitely will do, thanks a lot for your time guys.

**Comment by DarkTussin** [comment]
Hey sorry to be annoying, I ran Update-Package -reinstall and it says i'm using YoutubeExtractor 0.10.5, but I'm still getting forbidden errors on the links... specifically the first one x.x
